### ISSUE TITLE
accountsChanged event can not work

### ISSUE THREAD

**Issue by ysqi** [Conflux-Chain/conflux-portal#208]
当我DAPP网页启用，并连接到钱包后，有监听账号变化，但是当我在钱包中切换账号时，并没有接收到事件。

代码如下：
```js
conflux.enable().then(accounts => {
            if (accounts.length == 0) {
                alert("先使用钱包插件创建一个账户")
            } else { 
                conflux.autoRefreshOnNetworkChange = true;
                conflux.on("accountsChanged", function (accounts) {
                    alert("钱包切换账号拉！");
                    window.reload();
                })
            }
        }).catch(err => {
            alert(  err.toString());
        });
```

这里的  ` alert("钱包切换账号拉！");` 并没有被触发。

**Comment by yqrashawn** [comment]
据我了解, `conflux.enable().then` 里的 `then` 触发时, `accounts` 的长度一定不会是 0, 所以 `accountsChanged` 事件一直没有被监听. 可以参考[这里的例子](https://github.com/Conflux-Chain/conflux-portal/blob/343a0dd6bc9a682cd7828854a8276b200c58c76e/test/e2e/contract-test/contract.js#L721) 拿到 `accounts`.

**Comment by ysqi** [comment]
按你这么说，可能是会进入 else 的，也就是会有监听。

**Comment by yqrashawn** [comment]
抱歉, `accountsChanged` 事件的确会被监听, 但是该事件只会在
1. 初始化时 
2. accounts 从 0 个变成 1 个
3. 和从 1 个变成 0 个时触发

中途用户在 portal 的 ui 里切换账户时不会触发.

**Comment by ysqi** [comment]
那么这个Change仅仅是表示钱包有无账户的通知？

**Comment by yqrashawn** [comment]
是当前网站有无账户授权的通知，因为授权是以账户为单位，目前不支持同时授权多个账户，所以这个订阅目前的功能就是用来检测用户有没有取消授权
