### ISSUE TITLE
Portal should reject non-Conflux addresses

### ISSUE THREAD

**Issue by Thegaram** [Conflux-Chain/conflux-portal#240]
**Describe the bug**

Conflux addresses either start with `1` or `8`. Other addresses are definitely not Conflux addresses, but they're still accepted by Conflux Portal.

**To Reproduce (REQUIRED)**

1. Click on `Send`
2. Set `0x4084a68bef43a7530ef032cb1ced6a71ca875f88` as the recipient.
3. Send CFX or cUSDT.

The transaction might succeed, or the RPC might return an error. I think Portal should not allow sending such transactions in the first place.

**Expected behavior**

Conflux Portal should reject transactions with an invalid address. E.g. we could add a warning, something like `"Invalid address, are you sure this is a Conflux address?"`. This way, users will not accidentally send cTokens to an Ethereum deposit address (unless the address happens to start with 1 or 8, but at least the probability is lower).

**Screenshots**

I expect to see an error here:

![image](https://user-images.githubusercontent.com/7571518/94239131-a1111680-ff11-11ea-9e84-5ac72c4ed023.png)

**Browser details (please complete the following information):**
 - OS: OS X
 - Browser: Brave Version 1.14.81 Chromium: 85.0.4183.102 (Official Build) (64-bit)
 - ConfluxPortal Version 0.3.10

**Comment by yqrashawn** [comment]
This is resolved in version 0.5.3, portal now validates the address
