### ISSUE TITLE
Lost tokens?

### ISSUE THREAD

**Issue by rigg96ta** [Conflux-Chain/conflux-portal#244]
I transferred, or tried, 102.561 moon tokens to the my new conflux wallet from Metamask. After a few mins the screen flashed up an error message, which disappeared after a couple of second. The moon tokens are gone from my metamask wallet, but are not in my Conflux wallet- can you assist please??????

The transaction show as follows-

[moon token transaction.pdf](https://github.com/Conflux-Chain/conflux-portal/files/5283830/moon.token.transaction.pdf)

**Comment by Thegaram** [comment]
Did you transfer your tokens to the deposit address on MoonSwap or directly to your Conflux Portal address?

You cannot directly transfer tokens between Ethereum and Conflux addresses. You need to first transfer them to the deposit address (which is on Ethereum) using MetaMask, then wait for the ShuttleFlow cross-chain asset mapping protocol to release the corresponding tokens on Conflux.

**Comment by lozfoz123** [comment]
@Thegaram I transferred 0.5 ETH to the deposit address before noticing that minimum transfer is 0.75 ETH. The transfer was successful but the ETH hasnt turned up anywhere. Any idea where it may have gone or how to recover it?

**Comment by Thegaram** [comment]
You can send some more, once the sum is over the minimum amount you'll receive all of it.

**Comment by lozfoz123** [comment]
Ahh thats a relief then. Thanks!

**Comment by latif-fital** [comment]
Bonjour

S'il vous plait qui peut m'aider

J'ai envoyé 105 CFX depuis mon compte confluxportal mais sans créer de BNB vers mon compte metamask dans BCFX mais malheureusement depuis le matin je n'ai rien reçu

Cordialement

**Comment by Thegaram** [comment]
https://t.me/ConfluxFrench
