### ISSUE TITLE
TOKENS ARE NOT LOADING IN CONFLUXPORTAL WALLET

### ISSUE THREAD

**Issue by Narenz03** [Conflux-Chain/conflux-portal#245]

**Comment by Thegaram** [comment]
Could you please provide more details, context, screenshot, etc?

**Comment by Thegaram** [comment]
Most tokens seem to be displayed automatically. One exception I found is `DEX-BTC` (`0x8aaa75571e3e9fa40e1d6bd0fcd390c2bcf6ab45`).

**Comment by yqrashawn** [comment]
This should be resolved by now. Portal should automatically show tokens in https://confluxscan.io/tokens if your selected account has balance.
