### ISSUE TITLE
Popup window shows Oceanus instead of Tethys

### ISSUE THREAD

**Issue by Thegaram** [Conflux-Chain/conflux-portal#278]
**Describe the bug**

Popup window shows Oceanus instead of Tethys.

**To Reproduce (REQUIRED)**

1. Go to [MoonSwap Jupiter cUSDT](https://farm.moonswap.fi/farms/cUSDT-cETH%20MLP).
2. Click on *"Approve cUSDT-cETH MLP"*.

**Expected behavior**

I expect to see Conflux Tethys (as I do when I open the plugin manually).

**Screenshots**

![image](https://user-images.githubusercontent.com/7571518/97804465-6e64e700-1c50-11eb-8f52-647bd639abf4.png)

**Browser details (please complete the following information):**
 - OS: macOS Catalina
 - Browser: Chrome Version 86.0.4240.111 (Official Build) (x86_64)
 - ConfluxPortal v0.5.3

**Comment by yqrashawn** [comment]
fixed in #279
