### ISSUE TITLE
Doesn't work on Firefox

### ISSUE THREAD

**Issue by Nononitas** [Conflux-Chain/conflux-portal#304]
**Describe the bug**
If you open the addon it says: Connecting to Conflux Tethys Network.
After that: Oops! Something went wrong.
On Chrome it's working.

**To Reproduce (REQUIRED)**
Click on the addon.

**Expected behavior**
Connecting to the servers

**Screenshots**
https://i.postimg.cc/XqFYd0Yg/error.png

**Browser details (please complete the following information):**
 - Windows 10
 - Firefox 85.0.2 (64-Bit)
 - ConfluxPortal Version 0.5.11

**Comment by yqrashawn** [comment]
Hi, I can't reproduce the bug on my side. What happens when you visit https://wallet-main.confluxrpc.org/

**Comment by Nononitas** [comment]
Thanks for your answer.
I get the following message: Used HTTP Method is not allowed. POST or OPTIONS is required

**Comment by zctocm** [comment]
`curl -X POST --data '{"jsonrpc":"2.0","method":"cfx_clientVersion","id":1}' -H "Content-Type: application/json" https://wallet-main.confluxrpc.org/`
Hi, you can execute this line of code on your Terminal to see if it will return the correct result.
`{"jsonrpc":"2.0","result":"conflux-rust-1.1.0","id":1}`
If the correct result can be returned, it means that your network can access the RPC URL normally.

**Comment by Nononitas** [comment]
{"jsonrpc":"2.0","error":{"code":-32700,"message":"Parse error"},"id":null}

**Comment by zctocm** [comment]
Hi Nononitas, 
Usually, if there is a problem with the user’s network, the error shown in the picture will occur, but you can switch normally in chrome.
I suggest you can switch between Testnet and Tethys several times to have a try. 
And we will follow up on this issue

**Comment by criterionsz** [comment]
I have the same problem

**Comment by yqrashawn** [comment]
Hi @Nononitas @criterionsz,

Would you be able to take a screenshot of the debug console of portal? It will help us find the underlying problem. 

Here's a video showing how to open the debug console of portal.
https://user-images.githubusercontent.com/15090582/110729558-e45e0800-8259-11eb-96ce-7716623da562.mp4

**Comment by Nononitas** [comment]
Yes here you go https://youtu.be/VZfv20SE6PI

**Comment by confluxportal** [comment]
Same problem, Arch Linux, firefox 68.0.1

**Comment by confluxportal** [comment]
![image](https://user-images.githubusercontent.com/80961788/111782354-44107f00-88fc-11eb-9f71-b9753cd75bd9.png)
![image](https://user-images.githubusercontent.com/80961788/111782528-73bf8700-88fc-11eb-8eba-d9f8e822cf83.png)

**Comment by confluxportal** [comment]
![image](https://user-images.githubusercontent.com/80961788/111858267-f5ee9080-897a-11eb-8710-26610735bf11.png)
![image](https://user-images.githubusercontent.com/80961788/111858281-0acb2400-897b-11eb-99b0-7b85d52d8708.png)

**Comment by confluxportal** [comment]
If I can help you with anything else, just write to me.

**Comment by zctocm** [comment]
Hi @confluxportal @Nononitas 
Can you take a screenshot of the debug console in the portal?
We need more details in `Headers`, like this:
![CleanShot 2021-03-20 at 17 11 03@2x](https://user-images.githubusercontent.com/16474758/111865177-6956c900-89a0-11eb-8fd9-c0eaf53efde1.png)
.
Thanks a lot.

**Comment by confluxportal** [comment]
Ok, wait

**Comment by confluxportal** [comment]
![image](https://user-images.githubusercontent.com/80961788/111865452-5812ba00-89aa-11eb-93e5-d15c6c92258b.png)

**Comment by confluxportal** [comment]
I didn't quite understand where to press.

**Comment by zctocm** [comment]
hi @confluxportal 


https://user-images.githubusercontent.com/16474758/111868069-c491b700-89b2-11eb-8112-542f7bdd1ae3.mp4

**Comment by confluxportal** [comment]
https://user-images.githubusercontent.com/80961788/111868488-759d4f00-89bd-11eb-8e37-1bbffc92b09b.mp4
Not sure if I did it right ...

**Comment by zctocm** [comment]
hi @confluxportal , you should watch the video of @yqrashawn first, then you will know how to find the right place.

**Comment by confluxportal** [comment]
@zctocm its right?

https://user-images.githubusercontent.com/80961788/111869085-f0b43480-89c0-11eb-8310-a31294e5e0a2.mp4

**Comment by confluxportal** [comment]
If you do a clean install of Firefox, the extension works fine.

**Comment by confluxportal** [comment]
I tried disabling all extensions, it didn't help.

**Comment by confluxportal** [comment]
![image](https://user-images.githubusercontent.com/80961788/111869185-733cf400-89c1-11eb-8b87-0f5e5d83e461.png)

**Comment by confluxportal** [comment]
@zctocm @yqrashawn 
Hah, i find the problem, its too easy.
Go to Preferences, Privacy and Security, enable HTTPS-Only Mode in all windows.
With this setting, extension didnt work.

**Comment by confluxportal** [comment]
Enable it, and restart firefox

**Comment by Nononitas** [comment]
> 
> 
> @zctocm @yqrashawn
> Hah, i find the problem, its too easy.
> Go to Preferences, Privacy and Security, enable HTTPS-Only Mode in all windows.
> With this setting, extension didnt work.
> 
> Yeehooo, solved.

Yep same for me

**Comment by Nononitas** [comment]
Why can't we use https by the way?

**Comment by yqrashawn** [comment]
The bug is fixed in 0.6.1, you can find it here https://addons.mozilla.org/firefox/addon/conflux-portal/

**Comment by Nononitas** [comment]
Great thank you :)
