### ISSUE TITLE
Wallet not connecting in Chrome

### ISSUE THREAD

**Issue by airdrop29** [Conflux-Chain/conflux-portal#311]
FOR USER QUESTIONS, PLEASE DO NOT OPEN A GITHUB ISSUE - IT WILL NOT BE HANDLED HERE.

INSTEAD, PLEASE EMAIL PORTAL@CONFLUX-CHAIN.ORG WITH A DESCRIPTION OF YOUR PROBLEM.
Hi I've downloaded the conflux wallet and when I click on connect wallet it says install conflux portal wallet, I have installed and it's not reading it, as it keeps asking me to install the add on but I have done this twice so far and getting nowhere.

I'm not a coder so plain English to resolve would be good 

Thanks

**Comment by yqrashawn** [comment]
Hi @airdrop29 
Did you refresh the webpage after the installation? Chrome exiting only works on pages opened after its installation.

**Comment by yqrashawn** [comment]
I'll close this issue for now. Feel free to reopen this if it's still unable to connect.

**Comment by 65543** [comment]
Hi. I have similar problem. I have reinstall chrome. After that I again install conflux portal. When I want to import existing wallet I get  inavalid seed phrase. After I put 24 words recovery seed phrase my wallet recovers but there is no funds in my wallet also no transactions. ???

Can you please help? Thank you. U

**Comment by yqrashawn** [comment]
[**@65543**](https://github.com/65543) commented on [Apr 25, 2021, 11:51 PM GMT+8](https://github.com/Conflux-Chain/conflux-portal/issues/311#issuecomment-826346112 "2021-04-25T15:51:31Z - Replied by Github Reply Comments"):
> Hi. I have similar problem. I have reinstall chrome. After that I again install conflux portal. When I want to import existing wallet I get  inavalid seed phrase. After I put 24 words recovery seed phrase my wallet recovers but there is no funds in my wallet also no transactions. ???
> 
> Can you please help? Thank you. U

Hi, portal only supports 12 words seed phrase right now. You can try import single private key to use portal.

**Comment by 65543** [comment]
When 24 words will be supported. I dont have access to my funds.!

 

Tahnk you.
