### ISSUE TITLE
 Pending Balance

### ISSUE THREAD

**Issue by LoKoNaoX** [Conflux-Chain/conflux-portal#314]
Hi I am new mining, I think I did it correctly, I dowloaded a miner console and I added my conflux wallet but when I look my stats It said I have 0,1 pending balance. What that's means?, I have to wait or there is a minimun balance?. Because I see that I have 0 cfx on my wallet.
Thank you for your time  :)

**Comment by Habi82** [comment]
Hi, I have the same problem. I have chosen the beepool mining pool and on beepool.com I can see that I have already mined some coins, when I search for my wallet address. But in my confluc wallet I have as well 0 cfx.
Would be great if you would post your solution here when you solve it.

thx

**Comment by zctocm** [comment]
@LoKoNaoX @Habi82 Hi, I think you can contact the Miner company to ask whether they have already sent the CFX to your Conflux address first

**Comment by Habi82** [comment]
Thanks for the feedback
In the meantime I have received the coins. I think I just had to wait a bit.

**Comment by zctocm** [comment]
@LoKoNaoX @LoKoNaoX Ok, I will close this issue. 
Contact us when you encounter problems in using ConfluxPortal.
