### ISSUE TITLE
Lost token

### ISSUE THREAD

**Issue by 65543** [Conflux-Chain/conflux-portal#328]
I have problem with importing my wallet with memonic phrase. I have inserted my 12 words memonic phrase and it say it is invalid. ?? What can I do? Please help.

**Comment by yqrashawn** [comment]
Hi, can you check that all your 12 words are in the below bip39 wordlist? If there're words not included in this list, it's not the same hd wallet standard and portal don't support it right now.

https://github.com/bitcoinjs/bip39/blob/master/src/wordlists/english.json

**Comment by 65543** [comment]
Hi. Thank you for your answer. 

 

I can find 12 words in list. But it says that i have invalid seed phrase.

 

After that I try to put 24 words into box and I did get into conflux portal wallet. But there is no transactions and it is diferent wallet addrees etc. ???

 

Please help.

**Comment by yqrashawn** [comment]
Hi I just check the code of portal again and portal do support 24 words seed phrase.

> But there is no transactions and it is diferent wallet addrees

Where do you get the original address when you say it's different address?

**Comment by 65543** [comment]
Well. I don't know if it is different but there is no transactions and no
tokens in my wallet.  And also when I log into moonswap portal there is no
funds?

And also when  I want to check  recent conflux transactions in my Chrome
history nothing happens when I click on link.

Again I tried with 12 word and 24 word seed phrase.  And only with 24 word
seed phrase  I could enter my wallet. With no funds?

V pon., 26. apr. 2021 08:37 je oseba yqrashawn ***@***.***>
napisala:

**Comment by yqrashawn** [comment]
The rule of generate private key from seed phrase on different chain is different. Try export the private key of your address that has transactions and import it into portal through the [import account] button.

**Comment by 65543** [comment]
I do not understand. 

 

I have reinstall conflux portal on my chrome. 

 

I have inserted my 24 word phrase code and i have access to my wallet. But there is no transactions. 

 

I can do this for existing wallet but not for previous one??! I guess?

**Comment by 65543** [comment]
I have problem with this before. Ethgasstation.info

**Comment by 65543** [comment]
I have .json file but I cannot open it.

 

Conflux portal State Logs. Json file

**Comment by yqrashawn** [comment]
Do you use discord, can we discusses this there? https://discord.gg/nCuTfjZv

**Comment by 65543** [comment]
Sure we can. I would like to have some guidance from your side.

**Comment by 65543** [comment]
Whats your nick name on dischord?

**Comment by yqrashawn** [comment]
yqrashawn#4163

**Comment by 65543** [comment]
Uros#5525

 

Thats mine

**Comment by 65543** [comment]
So you want me to speak about this problem with comunity?

**Comment by yqrashawn** [comment]
Came out it's a typo in seed phrase. I'll close this issue.

**Comment by 65543** [comment]
Ok. Thank you!

 

Best regards.
