### ISSUE TITLE
Cannot import invalid private key.

### ISSUE THREAD

**Issue by rwelsh09** [Conflux-Chain/conflux-portal#331]
Hello,

I am trying to import my conflux address into the ConfluxPortal (or MetaMask) but I get the error "Cannot import invalid private key."

I have also tried converting my private key with https://www.confluxscan.io/address-converter
But, then I got different errors.

Any thoughts on how I can get this to work?

Thanks!

![image](https://user-images.githubusercontent.com/19652238/117557551-178dff00-b031-11eb-96d6-5991ae1524b4.png)

**Comment by yqrashawn** [comment]
Seems you are import the address instead of the private key. The private key should be 64 random hex characters.
