### ISSUE TITLE
Unable to install the ConfluxPortal extension

### ISSUE THREAD

**Issue by Jensonahn** [Conflux-Chain/conflux-portal#353]
**Describe the bug**
Unable to install the ConfluxPortal extension

**To Reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any
setup information to easily reproduce:

**Expected behavior**
A clear description of what you expected to happen.

**Screenshots**
![image](https://user-images.githubusercontent.com/87742399/126423160-c4eaaf57-5766-4ee4-a77d-203bdd6c9aca.png)

**Browser details (please complete the following information):**
 - OS: [MacBook Air (M1, 2020)]
 - Hardware Wallet [e.g. Trezor Firmware version 1.8.3, Ledger Nano S Firmware
   version 1.6.0]
 - Browser [e.g. Chrome Version 79.0.3945.79 (Official Build) (64-bit), Firefox
   Browser 71.0 (64-bit)]
 - ConfluxPortal Version [e.g. 5.0.2]

**Additional context (Error Messages, etc.)**

**Comment by yqrashawn** [comment]
We've submitted the extension to chrome web store and it's under review by google.

For now, you can try the [firefox one](https://addons.mozilla.org/en-US/firefox/addon/conflux-portal/) or download the extension at the [github release page](https://github.com/Conflux-Chain/conflux-portal/releases) and install it in [dev mode](https://developer.chrome.com/docs/extensions/mv3/faq/#faq-dev-01).

**Comment by Jensonahn** [comment]
Hi ! yqrashawn
Thanks to you, I've solved it. Thank you.
