### ISSUE TITLE
Does the conflux wallet have an API to exit the current account?

### ISSUE THREAD

**Issue by Taisen1991** [Conflux-Chain/conflux-portal#360]
In short

How to use window.conflux.xxx to achieve the same effect as the operation in the picture？

![image](https://user-images.githubusercontent.com/24730038/127134783-ac23ff64-2862-4537-9e8d-af7c0cf6d21f.png)

**Comment by yqrashawn** [comment]
No. There's no way that a dapp can lock a user's wallet.

**Comment by Taisen1991** [comment]
ok...
well,how to change account in the web.like window.conflux.xxxxx

the only way to change account is to operate ConfluxPortal,is it right?

**Comment by yqrashawn** [comment]
[**@Taisen1991**](https://github.com/Taisen1991) commented on [Jul 27, 2021, 6:21 PM GMT+8](https://github.com/Conflux-Chain/conflux-portal/issues/360#issuecomment-887394640 "2021-07-27T10:21:49Z - Replied by Github Reply Comments"):
> ok...
> well,how to change account in the web.like window.conflux.xxxxx
> 
> the only way to change account is to operate ConfluxPortal,is it right?

Yes. Dapp can only suggest user to change their account for now.

**Comment by Taisen1991** [comment]
> [**@Taisen1991**](https://github.com/Taisen1991) commented on [Jul 27, 2021, 6:21 PM GMT+8](https://github.com/Conflux-Chain/conflux-portal/issues/360#issuecomment-887394640):
> 
> > ok...
> > well,how to change account in the web.like window.conflux.xxxxx
> > the only way to change account is to operate ConfluxPortal,is it right?
> 
> Yes. Dapp can only suggest user to change their account for now.

ok, thanks!
