### ISSUE TITLE
如何像 E2E Test Dapp 中一样使用 Portal 创建合约以及使用其它功能？

### ISSUE THREAD

**Issue by LittleSound** [Conflux-Chain/conflux-portal#361]
在文档中给出了一个 [E2E Test Dapp](https://conflux-portal-docs.confluxnetwork.org/e2e_test_demo/) 测试程序，它可以创建合约，但是我在 [ConfluxPortal 文档](http://conflux-portal-docs.confluxnetwork.org/docs/portal/introduction/) 文档中没有找到关于这个功能的教程。所以我去尝试阅读了 E2E Test Dapp 的源码 ↓
portal-inpage.js
![image](https://user-images.githubusercontent.com/19204772/127479796-8c277dcc-6b1e-4a67-8b6c-1a1b15c75966.png)
contract.js
![image](https://user-images.githubusercontent.com/19204772/127479883-d4f77620-eec5-45ec-bf72-7a19b8ea7123.png)

发现它调用的是一个名为 confluxJS.Contract 的内部方法来创建合约，因此我没有办法参考它的代码去做，应为我拿不到这个 confluxJS，这个 confluxJS 似乎是 ConfluxPortal  内部的 js-conflux-sdk 实例，并且已经绑定好了当前登录的账户的私钥。而我也不知道如何通过 ConfluxPortal 拿到用户的私钥去创建合约（而且这个方案听起来也不是很安全）。
综上所述，如何使用 Portal 实现  E2E Test Dapp 演示里面的那些功能呢？

**Comment by angelia-yuqi-personal** [comment]
window.confluxJS is the conflux-js-sdk instance.

**Comment by LittleSound** [comment]
谢谢！
可以在文档里面补充一下作为参考。
