### ISSUE TITLE
chrome扩展程序中，申请测试水龙头失败

### ISSUE THREAD

**Issue by ltmhaha** [Conflux-Chain/conflux-portal#372]
{"code":2,"message":"Full node error or transaction not valid:Error: invalid argument 0: failed to create address from base32 string 0x170ddf9b9750c575db453eea6a041f4c8536785a: base32 string 0x170ddf9b9750c575db453eea6a041f4c8536785a is invalid format"}

**Comment by zctocm** [comment]
@ltmhaha hi, it works now

**Comment by ltmhaha** [comment]
sorry, its not work.
test-faucet.confluxnetwork.org 未发送任何数据。
ERR_EMPTY_RESPONSE

**Comment by ltmhaha** [comment]
> @ltmhaha hi, it works now

sorry, its not work.
test-faucet.confluxnetwork.org 未发送任何数据。
ERR_EMPTY_RESPONSE

**Comment by ltmhaha** [comment]
> @ltmhaha hi, it works now
open VPN 开启VPN的情况下：
该网页无法正常运作。test-faucet.confluxnetwork.org 未发送任何数据。ERR_EMPTY_RESPONSE
close VPN 关闭VPN的情况下：
无法访问此网站test-faucet.confluxnetwork.org 拒绝了我们的连接请求。ERR_CONNECTION_REFUSED

**Comment by Pana** [comment]
@ltmhaha It's working now

**Comment by Pana** [comment]
You can also use this faucet dapp http://faucet.confluxnetwork.org/

**Comment by ltmhaha** [comment]
> You can also use this faucet dapp http://faucet.confluxnetwork.org/

It's working now, thanks!
