### ISSUE TITLE
pending transaction

### ISSUE THREAD

**Issue by freakaleak** [Conflux-Chain/conflux-portal#378]
i made a transfer request to my gate.io wallet and the transaction was stuck on pending for more than 5 min. I then tried to cancel the transaction but the transaction is still stuck on pending. Please refer to the screenshot.

I am using google chrome browser on mac.

Conflux portal 0.6.9

Please assist in fixing the issue.

**Additional context (Error Messages, etc.)**
<img width="886" alt="Screenshot 2022-01-13 at 2 45 44 PM" src="https://user-images.githubusercontent.com/97666160/149301427-4a34529b-afe0-4884-8824-b7216d249e66.png">

**Comment by yqrashawn** [comment]
Hi,
You need to resend the same tx with higher gas price
Toggle on the customize transaction nonce option in settings -> advanced
send a new transaction with the same nonce (which is 1 from you screen shot)
set gas price to 300k drip

**Comment by freakaleak** [comment]
hi @yqrashawn

i tried what you said. Not sure if i did it correctly. Please see screenshot.
the new transaction is also stuck on pending.
<img width="602" alt="Screenshot 2022-01-13 at 3 43 11 PM" src="https://user-images.githubusercontent.com/97666160/149310860-13781cc9-437f-4492-b16b-556c84e5ff49.png">

**Comment by yqrashawn** [comment]
You need to 
1. toggle this on
![image](https://user-images.githubusercontent.com/15090582/149314799-ea36dce7-50ce-4b0a-a2c0-c8dd7112f3fa.png)

2. set the nonce to 1
![image](https://user-images.githubusercontent.com/15090582/149315017-f91dd4ad-01d4-44ce-bb81-5461de7d6356.png)
3. change this to at least 300000
![image](https://user-images.githubusercontent.com/15090582/149315114-969c511d-5244-47cd-a9c1-b8fead6ffb38.png)

**Comment by freakaleak** [comment]
Great it worked! 
My question now is why i didnt pay any transaction fee during my first cfx transfer (30 cfx)?
And now to transfer i havde to increase the gas price.

**Comment by yqrashawn** [comment]
Cause there're many other tx has higher gas price, which make you tx stuck there waiting forever.

**Comment by freakaleak** [comment]
Yes now just need to figure out how to keep a track on gas fees. Thank you good sir.
