### ISSUE TITLE
区块链新手提问

### ISSUE THREAD

**Issue by xiaozhu001** [Conflux-Chain/conflux-portal#69]
看了这个文档后，对于如何基于浏览器插件钱包开发应用有些疑问，我不是很清楚文档中出现的conflux.enable() 中的conflux变量是如何得到的。以及开发环境是什么，是基于node开发，还是什么，以及是否需要依赖？

**Comment by xiaods** [comment]
@xiaozhu001 谢谢提问，我已经引入到开发者网站，集中处理。以后有任何问题，请移步到开发者网站：https://github.com/Conflux-Chain/conflux-developer-site/issues  来提问，方便集中处理。谢谢。

**Comment by xiaods** [comment]
https://conflux-chain.github.io/conflux-portal-docs/docs/portal/Examples/e2e_test_demo  @xiaozhu001 
这个例子你有没有跑通过。

**Comment by xiaods** [comment]
我这块追一下。争取让人开发一个例子。

**Comment by xiaozhu001** [comment]
关于https://github.com/Conflux-Chain/conflux-portal/issues/69#issue-599245977 问题，我已经清楚了，对于这里实际上是一个理解的问题，我认为只要安装了钱包，那么在浏览器的console中通过window.conflux就能拿到对象，但是实际上是需要在一个网站中才能获取到对象，没有打开网站，也就是浏览器上方的网址是空的，那么你获取不到这个conflux对象。

**Comment by xiaods** [comment]
@xiaozhu001 Thanks
